[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Si no existe gracias.html, mostrar el “ok” en el index
[[redirects]]
  from = "/gracias.html"
  to = "/index.html?ok=1"
  status = 200
